project:
  type: website

website:
  title: "Criminological Research Methods"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clanfear/ioc_crm
format:
  html:
    theme: united
    css: styles.css



