---
title: "Seminar 10: Qualitative Data Analysis"
description: "Analyzing data from interviews, observation, and other qualitative collection methods"
author: "Caroline Lanskey"
date: "2025-11-25"
draft: false
---


Required reading:

* Rapley, T. (2011) ‘Some pragmatics of data analysis’, in D. Silverman (ed.) Qualitative Research, 3rd edition, London: Sage, pp. 273-290.
   * Download from Moodle

* Mason, J. (2002) Qualitative Researching, 2nd edition, London: Sage. Read chapter 8, ‘Organizing and indexing qualitative data’, pp. 147-172, and chapter 9, ‘Making convincing arguments with qualitative data’, pp. 173-204.

Further reading:

* Avis, M (2005) Is there an epistemology for qualitative research? In Holloway, I (ed) Qualitative Research in Health Care. Milton Keynes: Open University Press. Available at:https://lsms.ac/wp-content/uploads/2023/02/11_.pdf#page=22. (This book offers a helpful guide to different approaches to qualitative inquiry).

* Coffey, A. and Atkinson, P. (1996) Making Sense of Qualitative Data Analysis: Complementary research strategies, Thousand Oaks, CA: Sage.

* Ritchie, J. and Lewis, J. (2003) Qualitative Research Practice, London: Sage. Read chapters 8 to 10.

* Miles, M.B. and Huberman, A.M. (1994) Qualitative Data Analysis: An expanded sourcebook, 2nd ed., London: Sage.

* Robson, C. and McCartan, K. (2016) Real World Research: A resource for users of social research methods in applied settings, 4th ed., Chichester: Wiley. Read chapter 18, ‘The analysis and interpretation of qualitative data’, pp. 459-486, or equivalent chapter in an earlier edition.

* Silverman, D. (2013) Doing Qualitative Research, 4th ed., London: Sage. (See part 3.) 

* Charmaz, K. (2012). The power and potential of grounded theory. Medical sociology online, 6(3), 2-15. Available at: https://www.epicpeople.org/wp-content/uploads/2023/06/Charmaz-2012.pdf

* Flick U. (ed). 2004. The SAGE Handbook of Qualitative Data Analysis. SAGE Publications Ltd.