---
title: "Seminar 13: Document and Discourse Analysis"
description: "Analyzing text data"
author: "Loraine Gelsthorpe"
date: "2023-11-28"
draft: false
---

Required reading:

* Noaks, L., and Wincup, E. (2011) Criminological Research: Understanding qualitative methods, London: Sage Publications. Read chapter 7, ‘Using documentary evidence in qualitative research’, pp. 106-120.
Access ebook via iDiscover

* Cameron, D. and Panovic I. (2014) Working with Written Discourse, London: Sage. Read chapter 1, ‘Discourse and discourse analysis’, mainly the section ‘Power, knowledge and practice: discourse(s) and the construction of social reality’, pp. 6–12.
   * Access ebook via iDiscover
   * See also: https://www.sciencedirect.com/topics/social-sciences/discourse-analysis  (An introduction to discourse analysis).


Further reading:

* Plummer, K. (2001) Documents of Life 2: An invitation to a critical humanism, 2nd ed., London: Sage Publications.

* Wetherell M., Taylor S. and Yates, S.J. (2001) Discourse Theory and Practice: A reader, London: Sage Publications.

* Scott, J. (1990) A Matter of Record, Cambridge: Polity.

* Godfrey, B. (2012) ‘Historical and archival research methods’ in D. Gadd, S. Karstedt and S.F. Messner (eds) The Sage Handbook of Criminological Research Methods, London: Sage, pp. 159-174. 

* Hine, C. (2012) The Internet: Understanding qualitative research, Oxford: Oxford University Press.

* Irwin, S. and Winterton, A. (2011) Debates in Qualitative Secondary Analysis: Critical reflections: a Timescapes working paper, Leeds: Timescapes.
http://www.timescapes.leeds.ac.uk/assets/files/WP4-March-2011.pdf

* Prior, L. (2011) ‘Using documents in social research’, in D. Silverman (ed.) Qualitative Research, 3rd edition, London: Sage, pp. 93-110.
