---
title: "Bonus Seminar: Research Ethics"
description: ""
author: "Loraine Gelsthorpe"
date: "2023-12-01"
draft: false
---

Required reading:

* British Society of Criminology (2015) Statement of Ethics. Available at: http://www.britsoccrim.org/documents/BSCEthics2015.pdf
   * PLEASE READ THIS DOCUMENT BEFORE THE SEMINAR.

* Cowburn, M., Gelsthorpe, L. and Wahidin, A. (2017) (eds) Research Ethics in Criminology: Dilemmas, issues and solutions, London: Routledge. Read chapters 1, 11 and 13 – but otherwise dip in to the book.
Access ebook via iDiscover


Further reading:

* Israel, M. (2015) ‘Why care about ethics?’, in Research Ethics and Integrity for Social Scientists: Beyond regulatory compliance, 2nd ed., London: Sage.
   * Access ebook via iDiscover

* Burr, J. and Reynolds, P. (2010) ‘The wrong paradigm? Social research and the predicates of ethical scrutiny’, Research Ethics Review, 6(4): 128-133. http://dx.doi.org/10.1177/174701611000600404

* Cowburn, M. (2005) ‘Confidentiality and public protection: ethical dilemmas in qualitative research with adult male sex offenders’, Journal of Sexual Aggression, 11(1): 49-63. http://dx.doi.org/10.1080/13552600512331298284

* Dickson-Swift, V., James, E., Kippen, S. and Liamputtong, P. (2007) ‘Doing sensitive research: what challenges do qualitative researchers face?’, Qualitative Research, 7(3): 327-353.
http://dx.doi.org/10.1177/1468794107078515

* Dingwall, R. (2012) ‘How did we ever get into this mess? The rise of ethical regulation in the social sciences’, in K. Love (ed.) Ethics in Social Research, Bingley: Emerald, pp. 3-26.

* Mertens, D. and Ginsberg, P. (eds) (2009) Social Research Ethics, London: Sage.

