---
title: "Seminars 1–3: Introduction to Research"
subtitle: "Theory, questions, and answers"
description: "A week-long introduction to theory-guided empirical research in criminology"
author: "Charles Lanfear"
date: "2025-10-14"
draft: false
---

### Seminar 1 (Mon, Oct-13): Introduction to Theory-Guided Criminological Research (slides on Moodle)

* Tittle, C. R. (2015). Introduction: Theory and contemporary criminology. *The Handbook of Criminological Theory*. Wiley Blackwell, 1--17.
  * Download from Moodle
* Bottoms (2008) ‘The relationship between theory and research in criminology’ in R. King and E. Wincup (eds), *Doing Research on Crime and Justice*, Oxford: OUP, Chapter 3. pp. 75--116.
   * Download from Moodle


### [Seminar 2 (Tue, Oct-14): Developing and applying research questions and studying the causes of crime](https://clanfear.github.io/ioc_crm/_lectures/research-questions/slides_research-questions.html)

* [Huntington-Klein, N. (2022) *The Effect: An Introduction to Research Design and Causality*, New York, NY: Chapman and Hall/CRC Press.](https://theeffectbook.net/index.html)
   * Read pp. xix–18: (1) Introduction, (2) Chapter 1: Designing Research, and (3) Chapter 2: Research Questions

* Bueno de Mesquita, E. and Fowler, A. (2021) *Thinking Clearly with Data: A Guide to Quantitative Reasoning and Analysis*, Princeton, NJ: Princeton University Press. 
   * Read pp. 1–52: (1) Chapter 1: Thinking Clearly in a Data-Driven Age, (2) Chapter 2: Correlation: What Is It and What Is It Good For?, and (3) Causation: What Is It and What Is It Good For?

* Guba, E. G., & Lincoln, Y. S. (1994). Competing paradigms in qualitative research. In N. K. Denzin & Y. S. Lincoln (Eds.), *Handbook of qualitative research* (pp. 163–194). Sage. Download off Moodle

### Seminar 3 (Thu, Oct-15): Key challenges in criminological theory and research

* [Bernard, T.J. (1990) ‘Twenty years of testing theories: what have we learned and why?’, *Journal of Research in Crime and Delinquency*, 27(4): 325–347.](http://dx.doi.org/10.1177/0022427890027004002)
* Wikstrom, P-O H. (2017) ‘Character, circumstances, and the causes of crime: Towards an analytical criminology’ In A. Liebling, S. Maruna and L. McAra (eds) *Oxford Handbook of Criminology*, 6th edition. Oxford University Press. Pg 501-521 
  * Search for the title in Law Trove
* For workshop 1:
   * Pratt, T. C. (2015). Theory testing in criminology. *The Handbook of Criminological Theory*. Wiley Blackwell, 37-49.



