---
title: "Seminar 8: Ethnographic and Observational Research"
description: "Qualitative research using ethnographic methodology"
author: "Arushi Garg"
date: "2025-11-18"
draft: false
---

Slides on Moodle


Required reading:

* Haggerty et al (2021) ‘Introduction: The promises and challenges of crime ethnographies’ in  S.M. Bucerius et al (eds), *The Oxford Handbook of Ethnographies of Crime and Criminal Justice*, Oxford: OUP, Chapter 1. pp. 1-17

* Krishnan, S. (2015) ‘Dispatches from a ‘rogue’ ethnographer: Exploring homophobia and queer visibility in the field’, *Journal of the Anthropological Society of Oxford Online*, 7(1): 64–79

* Based on your research interests, please read any two ‘Further reading’ items below to be able to participate in classroom discussions.


Further reading:

* Crewe, B. (2006) ‘Prison drug dealing and the ethnographic lens’, *Howard Journal of Criminal Justice*, 45(4): 347-368.
[http://dx.doi.org/10.1111/j.1468-2311.2006.00428.x]()

* Hammersley, M. (1998) 'The nature of ethnography', in *Reading Ethnographic Research: A critical guide*, 2nd ed., London, Longman, pp. 1-20, or the equivalent chapter in the 1990 edition. (Download from Moodle)

* Jauregui, B. (2021) ‘Police Labor and Exploitation: Case Study of North India’ in S.M. Bucerius et al (eds), *The Oxford Handbook of Ethnographies of Crime and Criminal Justice*, Oxford: OUP, Chapter 23. pp. 488-511.

* Maher, L. (1997) 'Appendix: On reflexivity, reciprocity, and ethnographic research', in *Sexed Work: Gender, race and resistance in a Brooklyn drug market*, Oxford: Clarendon.

* Wakeman, S. (2014) ‘Fieldwork, biography and emotion: Doing criminological autoethnography’, *British Journal of Criminology*, 54(5): 705-721.

* Willis, R. (2019) ‘Observations online: Finding the ethical boundaries of Facebook research’, *Research Ethics*, 15(1): 1-17.

* Herrity, K, Schmidt, B.E. and Warr, J. "Sensory “Heteroglossia” and social control: Sensory methodology and method." In R. Faria and M. Dodge (eds), *Qualitative Research in Criminology: Cutting-edge Methods*. Cham: Springer International Publishing, 2022. 125-139.

* Padmanabhan, K. ‘How close is too close? Ethical tensions and reflections in the Breddon Centre.’ *Embracing the Unknown*. Policy Press, 2025. 145-155.

* Shah, A. (2017) ‘Ethnography? Participant observation, a potentially revolutionary praxis’, *HAU: Journal of Ethnographic Theory* 7(1): 45-59.

